DROP TABLE SZERZODESEK;
DROP TABLE DIAKOK;
DROP TABLE CSALADOK;
DROP TABLE BEFIZETESEK;

CREATE TABLE `SZERZODESEK` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `TAMOGATO` varchar(100) NOT NULL,
  `MUKODESI_KOLTSEG_TAMOGAS` int(11) NOT NULL,
  `EPITESI_HOZZAJARULAS` int(11) NOT NULL,
  `CSALAD_ID` int(11) NOT NULL,
  `EPITESI_HOZZAJARULAS_INDULO_EGYENLEG` int(11) NOT NULL,
  `MUKODESI_KOLTSEG_TAMOGAS_INDULO_EGYENLEG` int(11) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `DIAKOK` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NEV` varchar(100) NOT NULL,
  `OSZTALY` varchar(10) NOT NULL,
  `CSALAD_ID` int(11) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `CSALADOK` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `EMAIL1` varchar(100),
  `EMAIL2` varchar(100),
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `BEFIZETESEK` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `IMPORT_FORRAS` VARCHAR(100) NOT NULL,
  `IMPORT_IDOPONT` DATETIME NOT NULL,
  `KONYVELESI_NAP` DATE NOT NULL,
  `BEFIZETO_NEV` varchar(100) NOT NULL,
  `BEFIZETO_SZAMLASZAM` varchar(100) NOT NULL,
  `OSSZEG` int NOT NULL,
  `KOZLEMENY` varchar(256),
  `STATUSZ` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `EGYENLEG_TETEL` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `SZERZODES_ID` int(11) NOT NULL,
  `MEGNEVEZES` varchar(256) NOT NULL,
  `TERHELES_OSSZEG` int NOT NULL,
  `BEFIZETES_ID` int(11),
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

